name: Fetch DATEX DIR Ouest

on:
  schedule:
    - cron: "0 */6 * * *"  # exécution toutes les 6 heures
  workflow_dispatch:        # exécution manuelle possible

permissions:
  contents: write  # autorise le push via GITHUB_TOKEN

jobs:
  update-datex:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v4

      - name: Configuration de Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Installation des dépendances
        run: |
          pip install requests lxml

      - name: Liste des fichiers (debug)
        run: |
          pwd
          ls -R

      - name: Exécution du script DATEX DIR Ouest
        run: |
          python scripts/fetch_datex_diro.py

      - name: Commit et push des fichiers générés
        run: |
          git config user.name "DATEX Bot"
          git config user.email "actions@github.com"
          git add data/
          git diff --cached --quiet || git commit -m "🤖 MAJ DATEX DIR Ouest - $(date '+%Y-%m-%d %H:%M')"
          git push
